### ISSUE TITLE
dependency version

### ISSUE THREAD

**Issue by zhaoyu-li** [guaguakai/surrogate-optimization-learning#1]
Hi, can you please provide your dependencies version? It seems like there is a problem when installing all the newest dependencies.

**Comment by guaguakai** [comment]
This is the list I got from my conda environment. I have checked that this environment works on my server, but I haven't checked whether a fresh setup would work or not (hopefully it works. I am aware of that some newer scipy versions could cause conflict). Let me know how it goes. I am happy to make this repo more accessible to general public. 

Some additional dependency version:
qpth 0.0.15
cvxpylayers 0.1.3
scipy 1.3.1
torch-geometric 1.3.2

```
# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: linux-64
_libgcc_mutex=0.1=main
autograd=1.2=py_1
blas=1.0=mkl
ca-certificates=2019.5.15=0
certifi=2019.6.16=py36_0
cffi=1.12.3=py36h2e261b9_0
cudatoolkit=10.0.130=0
cvxpy=1.0.24=py36_0
cycler=0.10.0=py_1
dbus=1.13.2=h714fa37_1
dill=0.2.9=py36_0
ecos=2.0.5=py36_0
expat=2.2.5=he1b5a44_1003
fontconfig=2.13.1=he4413a7_1000
freetype=2.9.1=h8a8886c_1
future=0.17.1=py36_1000
gettext=0.19.8.1=hc5be6a0_1002
glib=2.56.2=had28632_1001
gst-plugins-base=1.14.0=hbbd80ab_1
gstreamer=1.14.0=hb453b48_1
gurobi=8.1.1=py36_0
icu=58.2=hf484d3e_1000
intel-openmp=2019.4=243
joblib=0.13.2=py36_0
jpeg=9b=h024ee3a_2
kiwisolver=1.1.0=py36hc9558a2_0
lapack=3.6.1=ha44fe06_2
libedit=3.1.20181209=hc058e9b_0
libffi=3.2.1=hd88cf55_4
libgcc=7.2.0=h69d50b8_2
libgcc-ng=9.1.0=hdf63c60_0
libgfortran=3.0.0=1
libgfortran-ng=7.3.0=hdf63c60_0
libiconv=1.15=h516909a_1005
libpng=1.6.37=hbc83047_0
libstdcxx-ng=9.1.0=hdf63c60_0
libtiff=4.0.10=h2733197_2
libuuid=2.32.1=h14c3975_1000
libxcb=1.13=h14c3975_1002
libxml2=2.9.9=h13577e0_0
matplotlib=3.1.0=py36_1
matplotlib-base=3.1.0=py36hfd891ef_1
mkl=2019.4=243
mkl-service=2.0.2=py36h7b6447c_0
mkl_fft=1.0.12=py36ha843d7b_0
mkl_random=1.0.2=py36hd81dba3_0
multiprocess=0.70.4=py36_0
ncurses=6.1=he6710b0_1
ninja=1.9.0=py36hfd86e86_0
numpy=1.16.4=py36h7e9f1db_0
numpy-base=1.16.4=py36hde5b4d6_0
olefile=0.46=py36_0
openssl=1.1.1c=h7b6447c_1
osqp=0.5.0=py36h035aef0_1
pcre=8.43=he6710b0_0
pillow=6.0.0=py36h34e0f95_0
pip=19.1.1=py36_0
proj=6.2.0=hc80f0dc_1
pthread-stubs=0.4=h14c3975_1001
pycparser=2.19=py36_0
pyparsing=2.4.0=py_0
pyproj=2.4.1=py36ha987037_0
pyqt=5.6.0=py36h13b7fb3_1008
python=3.6.9=h265db76_0
python-dateutil=2.8.0=py_0
pytorch=1.1.0=py3.6_cuda10.0.130_cudnn7.5.1_0
qt=5.6.3=h8bf5577_3
readline=7.0=h7b6447c_5
scikit-learn=0.21.2=py36hd81dba3_0
scipy=1.2.1=py36h7c811a0_0
scs=1.2.6=py36_0
setuptools=41.0.1=py36_0
sip=4.18.1=py36hf484d3e_1000
six=1.12.0=py36_0
sqlite=3.30.0=h7b6447c_0
termcolor=1.1.0=py36_0
tk=8.6.9=hed695b0_1002
torchvision=0.3.0=py36_cu10.0.130_1
tornado=6.0.3=py36h516909a_0
tqdm=4.32.2=py_0
wheel=0.33.4=py36_0
xlrd=1.2.0=py36_0
xorg-libxau=1.0.9=h14c3975_0
xorg-libxdmcp=1.1.3=h516909a_0
xz=5.2.4=h14c3975_4
zlib=1.2.11=h7b6447c_3
zstd=1.3.7=h0b5b093_0
```

**Comment by zhaoyu-li** [comment]
thanks！

**Comment by zhaoyu-li** [comment]
Hi, it seems like there is still a problem when I install cvxpylayers==0.1.3:

ERROR: Some build dependencies for cvxpy>=1.1.0a4 from https://files.pythonhosted.org/packages/e6/3b/6a6650ed48503c4e4b2f497ce40517fe427f3cfacfc8fb43ff52f89bc4c8/cvxpy-1.1.8.tar.gz#sha256=444068d4eda9ffcd43578895174489d4cef36b28ba7ae8a96ab9ef9571d2b4ff (from cvxpylayers) conflict with the backend dependencies: numpy==1.13.3 is incompatible with numpy>=1.15.

I see your numpy version >=1.15, but the terminal says that the numpy version should < 1.15.

**Comment by guaguakai** [comment]
I built a fresh conda environment and fixed the potential syntax issue of all the latest library versions (so hopefully there won't be a dependency issue on numpy and cvxpylayers). I have pushed the code and put a newer `package-list.txt` file in the repo. Would you mind updating to the newer environment and letting me know if that works for you? Let me know if it is still not working.
